#ifndef __CONFIG_H__
#define __CONFIG_H__

#include "dir.h"

#define GRIP_DIR            ".grip"
#define TRIGRAMS_LIST_FNAME "index"
#define TRIGRAMS_DATA_FNAME "data"
#define FILE_LIST_FNAME     "files"
#define TMP_SUFFIX          ".tmp"

#define TRIGRAMS_LIST_PATH  GRIP_DIR PATH_DELIMITER_S TRIGRAMS_LIST_FNAME
#define TRIGRAMS_DATA_PATH  GRIP_DIR PATH_DELIMITER_S TRIGRAMS_DATA_FNAME
#define FILE_LIST_PATH      GRIP_DIR PATH_DELIMITER_S FILE_LIST_FNAME

#define TRIGRAMS_LIST_PATH_TMP  TRIGRAMS_LIST_PATH TMP_SUFFIX
#define TRIGRAMS_DATA_PATH_TMP  TRIGRAMS_DATA_PATH TMP_SUFFIX
#define FILE_LIST_PATH_TMP      FILE_LIST_PATH TMP_SUFFIX

#endif
